fix: ready to use cli with create-clip command
donkeyclip/cli pull request #75
Opened 2023-01-19 20:01 UTC by prieston

2023-01-20 15:09 UTC, alexdor requested changes

2023-01-20 15:09 UTC, alexdor commented on src/index.js
> +// utils.cloneGitRepo(command, projectName);
Do we need these here?

2023-01-20 15:09 UTC, alexdor commented on src/utils.js
> +// const copyfiles = require("copyfiles");
```suggestion
```

2023-01-20 15:09 UTC, alexdor commented on src/utils.js
> +  // await copyfiles([clipFrom, clipDest], { up: 3 });
```suggestion
```

2023-01-20 15:09 UTC, alexdor commented on src/utils.js
> +        "./",
Shouldn't this be the same?
```suggestion
        ".",
```

2023-01-20 15:09 UTC, alexdor commented on src/utils.js
> +      const tsconfig = path.join("./", projectName, "tsconfig.json");
The ./ works only for unix machines so this will break on windows

2023-01-20 15:09 UTC, alexdor commented on src/utils.js
> +      await rimraf("./**/*.ts");
The ./ works only for unix machines so this will break on windows

2023-01-21 14:00 UTC, prieston commented on src/index.js
> +// utils.cloneGitRepo(command, projectName);
nope

2023-01-21 18:09 UTC, alexdor reviewed
Don’t we also need to update the docs?

also, I’ve seen the command “npm create” been mentioned in a lot of packages (when initializing something) should we support it?

2023-01-23 20:03 UTC, alexdor approved these changes

2023-01-23 20:03 UTC, merged